# argocd-apps/canary-services.yaml â†’ DELETE external service!
---
apiVersion: v1
kind: Service
metadata:
  name: computer-academy-stable
  namespace: computer-academy
spec:
  selector:
    app: computer-academy
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: computer-academy-canary
  namespace: computer-academy
spec:
  selector:
    app: computer-academy
  ports:
  - port: 80
    targetPort: 3000

